### ISSUE TITLE
RunTogether endpoint down?

### ISSUE THREAD

**Issue by domfennell** [RunTogether/opendata#2]
Hi @dolkensp, hope you're well.

Just been on the http://status.openactive.io/ and noticed that the endpoint is down and returning a Cloudflare "524 error".

Apologies if you're already aware of this issue - do let us know when you think it might be fixed.

Thanks.

**Comment by peter-dolkens** [comment]
Hi @domfennell 

Sorry I forgot to respond here - this feed should be back up and running now

**Comment by domfennell** [comment]
Lovely. Thanks for the update, @dolkensp. Have a good afternoon.

**Comment by nishaldesai** [comment]
Hi @dolkensp - season's greetings!

We've been monitoring the Run Together OpenActive API endpoint stability, just wanted to flag to see if this is expected behaviour?

In December the endpoint has become unresponsive a few times - but only for a few minutes at a time. However, it's now been down since Dec 19th.

Just wanted to make sure everything is all ready for the January get-fit rush across the data users that might be using the England Athletics feed.

Please let me know if I can help with anything.

Festive wishes :)

Nish

**Comment by domfennell** [comment]
Hi @dolkensp, hope you had a good break.

Should we start a new issue for @nishaldesai's follow-up question about the England Athletics endpoint apparently being down?
